{
 "title": "Clusters Overview",
 "tags": [ "ACM" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "cluster", "label": "Cluster", "query": { "query": "label_values(cluster)" } }
  ]
 },
 "panels": [
  {
   "title": "Cluster Basic Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cluster Version",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "cluster_version{type=\"current\"}",
       "legendFormat": "{{ version }}"
      }
     ]
    },
    {
     "title": "API Servers Up",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 8, "x": 4, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "up{job=\"apiserver\",cluster=\"$cluster\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Cluster Operators Status",
     "type": "table",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "cluster_operator_up{cluster=\"local-cluster\",job=\"cluster-version-operator\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Number of Nodes",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "sum(node_os_info)" }
     ]
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of Nodes",
     "type": "timeseries",
     "description": "Per node type",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "mapi_machine_set_status_replicas",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Node Status",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kube_node_status_condition{condition=\"Ready\",job=\"kube-state-metrics\",status=\"true\",cluster=\"$cluster\"}",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "CPU usage per node",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "instance:node_cpu_utilisation:rate1m{cluster=\"$cluster\", job=\"node-exporter\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Memory  usage per node",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "instance:node_memory_utilisation:ratio{cluster=\"$cluster\", job=\"node-exporter\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Application",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Unhealthy Pod",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(kube_pod_status_phase{cluster=\"$cluster\",phase=~\"Failed|Pending|Unknown\"}) by (namespace) != 0",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "Number of available deployconfig",
     "type": "stat",
     "description": "Non openshift namespaces",
     "gridPos": { "h": 8, "w": 5, "x": 12, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(openshift_deploymentconfig_status_replicas_available{namespace!~\"openshift.*\"})"
      }
     ]
    },
    {
     "title": "Number of available deployments",
     "type": "stat",
     "description": "Deployment counts in non openshift projects",
     "gridPos": { "h": 8, "w": 5, "x": 17, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_deployment_status_condition{condition=\"Available\", status=\"true\", namespace!~\"openshift.*\"})"
      }
     ]
    },
    {
     "title": "CPU Utilisation",
     "type": "table",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(kube_pod_owner{cluster=\"$cluster\"}) by (namespace)"
      },
      {
       "expr": "namespace_workload_pod:kube_pod_owner:relabel:avg{cluster=\"$cluster\"}"
      },
      {
       "expr": "node_namespace_pod_container:container_cpu_usage_seconds_total:sum{cluster=\"$cluster\"}"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests:sum{cluster=\"$cluster\", resource=\"cpu\"}) by (namespace)"
      },
      {
       "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum{cluster=\"$cluster\"}) by (namespace) / sum(kube_pod_container_resource_requests:sum{cluster=\"$cluster\", resource=\"cpu\"}) by (namespace)"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits:sum{cluster=\"$cluster\", resource=\"cpu\"}) by (namespace)"
      },
      {
       "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum{cluster=\"$cluster\"}) by (namespace) / sum(kube_pod_container_resource_limits:sum{cluster=\"$cluster\", resource=\"cpu\"}) by (namespace)"
      }
     ]
    },
    {
     "title": "Memory Utilisation",
     "type": "table",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(kube_pod_owner{cluster=\"$cluster\"}) by (namespace)"
      },
      {
       "expr": "namespace_workload_pod:kube_pod_owner:relabel:avg{cluster=\"$cluster\"}"
      },
      {
       "expr": "sum(container_memory_rss:sum{cluster=\"$cluster\", container!=\"\"}) by (namespace)"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests:sum{cluster=\"$cluster\", resource=\"memory\"}) by (namespace)"
      },
      {
       "expr": "sum(container_memory_rss:sum{cluster=\"$cluster\", container!=\"\"}) by (namespace) / sum(kube_pod_container_resource_requests:sum{cluster=\"$cluster\", resource=\"memory\"}) by (namespace)"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits:sum{cluster=\"$cluster\", resource=\"memory\"}) by (namespace)"
      },
      {
       "expr": "sum(container_memory_rss:sum{cluster=\"$cluster\", container!=\"\"}) by (namespace) / sum(kube_pod_container_resource_limits:sum{cluster=\"$cluster\", resource=\"memory\"}) by (namespace)"
      }
     ]
    }
   ]
  },
  {
   "title": "Ingress Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Front - HTTP responses code",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "short", "label": "responses" }
     ],
     "targets": [
      {
       "expr": "rate(haproxy_frontend_http_responses_total{cluster=\"$cluster\",}[$__rate_interval])",
       "legendFormat": "{{ code }} {{ frontend }} {{pod}}"
      }
     ]
    },
    {
     "title": "Back - HTTP responses code",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 40 },
     "yaxes": [
      { "format": "short", "label": "responses" }
     ],
     "targets": [
      {
       "expr": "rate(haproxy_backend_http_responses_total{cluster=\"$cluster\"}[$__rate_interval])",
       "legendFormat": "{{ code }} {{ backend }} NS:{{exported_namespace}} Route:{{route}}"
      }
     ]
    },
    {
     "title": "Back - http average connect latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 53 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "haproxy_backend_http_average_connect_latency_milliseconds{cluster=\"$cluster\"}",
       "legendFormat": "{{ backend }} NS:{{exported_namespace}} Route:{{route}}"
      }
     ]
    },
    {
     "title": "Server - HTTP responses code",
     "type": "graph",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 61 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(haproxy_server_http_responses_total{cluster=\"$cluster\"}[$__rate_interval])",
       "legendFormat": "{{ code }} {{ exported_pod }} {{ server }}"
      }
     ]
    }
   ]
  }
 ]
}